
```{r}
library(here)
library(tidyverse)
library(PNWColors)
library(knitr)
library(cowplot)
library(ggrepel)


here::here()
data_dir <- here("03_func", "inphared")
meta_dir <- here("03_func", "03_metadata")
raw_dir <- here("03_func", "inphared", "03_inph_raw")
figs_dir <- here("03_func", "inphared", "figs")

pal2 <- c("#015b58", "#5962b5")
pal2.flip <- c("#5962b5", "#015b58")
hmm <- read.csv(here(data_dir, "inphared_hmm_comp2.csv"), row.names=1 ) ##d_amg
hmm$comp3 <- hmm$Nog.abbrev
#hmm$comp3 <- ifelse(hmm$sporulation_hit!="no_hit", "Sporulation", hmm$comp3)
hmm$comp3 <- ifelse(hmm$comp2=="Unknown (S, No Hits)", hmm$comp2, hmm$comp3)

hmm$comp3 <- ifelse(hmm$sporulation_hit!="no_hit", "Sporulation", hmm$comp3)


hmm <- subset(hmm, hmm$ref=="ref_seq")

hmm.brief <- select(hmm, phage, mmseqs_qseqid, predicted_label, COG.broad, detailed, comp, comp2, comp3, spor, Host, life_bool)

hmm.brief <- subset(hmm.brief, hmm.brief$comp2!="Unknown (S, No Hits)" & hmm.brief$comp2!="Phage-associated")

hmm.brief <- subset(hmm.brief, hmm.brief$comp2!="Unknown (S, No Hits)" & hmm.brief$comp2!="Phage-associated")

### everything is currently sporulating only
#hmm.brief <- unite(hmm.brief, lifestyle_spor, spor, predicted_label, sep = "_", remove=FALSE)
```



```{r}
# add host sporulation to amg
#d.amg <- subset(d.amg, d.amg$phage=="OX639564") ##weird lifestyle data, remove for now
#d.amg <- all %>% rename(spor_host = f_spor, comp3 = comp3, gene_description = query, Lifestyle = predicted_label)



d.amg <- hmm.brief %>% rename(spor_host = Host, Lifestyle = predicted_label)
d.amg %>% group_by(Lifestyle) %>% summarise(n=n())

inph.damg <- d.amg
```


First we summarize the number of phages infecting hosts that are lytic/temp 
```{r}
d.vir <- d.amg %>% group_by(life_bool, Lifestyle) %>% summarise(n=n())

```

```{r}
p.signif <- 1e-3

k_treshold <- 8
```



First we summarize the number of phages infecting hosts that sporulate or not
```{r}

total_temp <- 
  d.vir %>% 
  filter(life_bool) %>% 
  pull(n) 



total_vir <- 
  d.vir %>% 
  filter(!life_bool) %>% 
  pull(n) 


```


For each gene we ask how many times it is found in a temp or lytic phage.
```{r}

# Summarise total number of sporulators and non sporulators
d.amg.sum <- d.amg %>%
  # filter(str_detect(header, regex("sporulation", ignore_case = T))) %>%
  filter(!is.na(comp3)) %>% 
  filter(!is.na(life_bool)) %>% 
  group_by(comp3, life_bool, COG.broad) %>% #category removed, lifestyle added
  summarise(n = n()) %>%
  arrange(desc(n))

d.amg.sum %>%
  ggplot(aes(comp3, n, color = life_bool))+
  geom_point(shape=21, size=2)+
  #facet_wrap(~spor_host, scales = "free_y")+ ## category removed, lifestyle added
  coord_flip()+
  theme_bw()



d.amg.sum$rel <- ifelse(d.amg.sum$life_bool==TRUE, d.amg.sum$n/total_temp*100, d.amg.sum$n/total_vir*100)


rel <- d.amg.sum %>%
  ggplot(aes(comp3, rel, color = life_bool))+
  geom_point(shape=21, size=2)+
  ylab( "normalized (%) occurence from AMG genes") +
  coord_flip()+ theme_bw() + labs(color="Lifestyle") + scale_color_hue(labels = c("Virulent", "Temperate")) 
  


rel

# ggsave(here("refseq/out-dir/rel_lifestyle_spor_enrich.png"), height =3 ,width = 6)


```



```{r}
temp_enrich <- 
  d.amg %>% 
  
  # Summarize KOs by host sporulation
 mutate(life_bool = case_when(
    life_bool ~ "temperate",
    !life_bool ~ "virulent"
  )) %>% 
  filter(!is.na(comp3)) %>% 
  group_by(comp3, life_bool, COG.broad) %>% 
  summarise(n=n(), .groups = "drop") %>% 
  pivot_wider(values_from = n, names_from = life_bool, values_fill = 0) %>% 
   
    # q	: the number of white balls drawn without replacement 
    # from an urn which contains both black and white balls.
    # >>> AMG (specific gene) in viruses infecting sporulators
    mutate(q = temperate) %>% 
    
    # m	:the number of white balls in the urn.
    # >>> number of viruses infecting sporulators in the pool
    mutate(m = total_temp) %>% 
    
    # n	:the number of black balls in the urn.
    # >>> number of viruses infecting non-sporulators in the pool
    mutate(n = total_vir) %>% 
    
    # k: the number of balls drawn from the urn, hence must be in 0,1,., m+n.
    # >>> Total AMG (specific gene) detected in viruses
    mutate(k = virulent + temperate) %>% 
    
    mutate(p.val = signif (phyper(q, m, n, k, lower.tail =F),5)) #%>% 
  # Adjust Pvalue for multiple testing
 #   mutate(p.adj = signif (p.adjust(p.val, method = "BH"),5)) %>% 
  # mark significantly enriched genes
  # mutate(significant = (p.adj < p.signif) & (k>k_treshold))
#pval adjust done later
  
temp_enrich$enriched <- "temperate"
p_temp.all <- temp_enrich
```


```{r}
vir_enrich <- 
  d.amg %>% 
  
  # Summarize KOs by host sporulation
 mutate(life_bool = case_when(
    life_bool ~ "temperate",
    !life_bool ~ "virulent"
  )) %>% 
  filter(!is.na(comp3)) %>% 
  group_by(comp3, life_bool, COG.broad) %>% 
  summarise(n=n(), .groups = "drop") %>% 
  pivot_wider(values_from = n, names_from = life_bool, values_fill = 0) %>% 
   
    # q	: the number of white balls drawn without replacement 
    # from an urn which contains both black and white balls.
    # >>> AMG (specific gene) in viruses infecting that lifestyle
    mutate(q = virulent) %>% 
    
    # m	:the number of white balls in the urn.
    # >>> number of viruses of that lifestyle
    mutate(m = total_vir) %>% 
    
    # n	:the number of black balls in the urn.
    # >>> number of viruses infecting the other lifestyle
    mutate(n = total_temp) %>% 
    
    # k: the number of balls drawn from the urn, hence must be in 0,1,., m+n.
    # >>> Total AMG (specific gene) across all lifestyles
    mutate(k = virulent + temperate) %>% 
    
    mutate(p.val = signif (phyper(q, m, n, k, lower.tail =F),5)) #%>% 
  # Adjust Pvalue for multiple testing
    #mutate(p.adj = signif (p.adjust(p.val, method = "BH"),5)) %>% 
  # mark significantly enriched genes
   #mutate(significant = (p.adj < p.signif) & (k>k_treshold))

#pval adjust done later

vir_enrich$enriched <- "virulent"
p_vir.all <- vir_enrich


```

```{r}

## pval adjustement for all?

all.pv <- rbind(p_temp.all, p_vir.all)
# all.pv$og.adj <- all.pv$p.adj


## i adjust p.val original, NOT p.adj (from original?)
  # Adjust Pvalue for multiple testing
all.pv.adj <-  all.pv %>%  mutate(p.adj = signif (p.adjust(p.val, method = "BH"),5)) %>% 
  # mark significantly enriched genes
   mutate(significant = (p.adj < p.signif) & (k>k_treshold))

#all.pv.adj <- merge(all.pv.adj, kegg.enrich, by.x="comp3", by.y="comp3", all.x=TRUE, all.y=FALSE)

##parA is **mostly** in temperate clostridium difficile phage -- think this might be a sampling issue.
```



Plot enrichment results

```{r}
# labels for significant genes
labels <- 
  d.amg %>% 
  select(comp3, COG.broad) %>% 
  distinct() %>% 
  #filter(comp3 %in% all.pv.adj$comp3[d.vir$significant]) %>% 
  mutate(lab = str_remove(comp3, "[;|\\[].*")) %>% 
  group_by(comp3) %>% 
  summarise(p_lab = str_c(lab, collapse = "\n")) #%>% 
  #adjustment of one label
  #mutate(p_lab = if_else(comp3 == "K00558", paste0(p_lab, "\n"), p_lab))

d_enrich <- left_join(all.pv.adj, labels,  by = "comp3") 

d_enrich$real <- ifelse(d_enrich$significant==TRUE, d_enrich$comp3, NA)


  #mark sporulation genes
d_enrich <- d_enrich %>% 
  mutate(spor_gene = if_else(comp3 %in% unique(d_enrich$comp3),
         "Spoulation genes", "Other genes"))

# plot
p <-
  d_enrich %>% 
  filter(k>0) %>%
  ggplot(aes(k,-log10(p.adj+1e-120)))+
  geom_hline(yintercept = -log10(p.signif), linetype=2, color="grey", size = 1)+
  geom_vline(xintercept = k_treshold, linetype=2, color="grey", size = 1)+
  
 geom_text_repel(aes(label = real), size = 3, na.rm = T, point.padding = 0, min.segment.length = 0,seed = 123) +
  
  geom_jitter(aes(fill = significant),width = 0.05, height = 0.05,
              shape=21, size=3, stroke = 1, show.legend = F)+
  scale_fill_manual(values=pal2)+
  #scale_fill_viridis_d(direction = -1, alpha = 0.5)+
  theme_classic()+
  facet_wrap(~ enriched %>% fct_rev(), ncol = 2) +
  panel_border(color = "black")+
  scale_x_continuous(trans = "log2", breaks = (2^(0:12)))+
  xlab("Sample size\nNo. homologs detected (log2)")+
  ylab("Enrichment (-log10 adj. P-value)")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        strip.background = element_blank(),
        strip.text = element_text(face = "bold"))

 ggsave(here(figs_dir, "inph_lifestyle_AVG_enriched.png"), height =4 ,width = 6)
p

```



```{r}
sig <- subset(all.pv.adj, all.pv.adj$significant==TRUE)


sig.list <- select(sig, comp3, enriched)
sig.list$life_bool <- TRUE
sig.list2 <- select(sig, comp3, enriched)
sig.list2$life_bool <- FALSE
sig.list <- rbind(sig.list, sig.list2)




# Summarise total number of sporulators and non sporulators
d.amg.sum <- d.amg %>%
  # filter(str_detect(header, regex("sporulation", ignore_case = T))) %>%
  filter(!is.na(comp3), ) %>% 
  filter(!is.na(life_bool)) %>% 
  group_by(comp3, life_bool, COG.broad) %>% #category removed, lifestyle added
  summarise(n = n()) %>%
  arrange(desc(n))

d.amg.sum %>%
  ggplot(aes(comp3, n, color = life_bool))+
  geom_point(shape=21, size=2)+
  #facet_wrap(~spor_host, scales = "free_y")+ ## category removed, lifestyle added
  coord_flip()+
  theme_bw()



d.amg.sum$rel <- ifelse(d.amg.sum$life_bool==TRUE, d.amg.sum$n/total_temp*100, d.amg.sum$n/total_vir*100)

d.amg.sig <- sig.list %>%
  full_join(d.amg.sum, by = c("comp3", "life_bool"))

d.amg.sig$enriched[is.na(d.amg.sig$enriched)] <- "Not Enriched"
#d.amg.sig$rel[is.na(d.amg.sig$rel)] <- 0

d.amg.sig <- d.amg.sig %>%
  mutate(enriched_facet = fct_rev(enriched))


d.amg.sig <- d.amg.sig %>%
  group_by(enriched_facet) %>%
  mutate(comp3 = fct_drop(factor(comp3))) %>%
  ungroup()


rel <- d.amg.sig %>%
  ggplot(aes(comp3, rel, fill= life_bool)) +
  #geom_point(shape = 21, size = 2) +
  geom_bar(stat="identity", position=position_dodge()) +
  ylab("Normalized (%) Relative Abundance of Gene") +
  theme_bw() +
  labs(color = "Lifestyle", fill = "Phage Lifestyle") +
  scale_color_hue(labels = c("Virulent", "Temperate")) +
  facet_wrap(~ enriched_facet, scales = "free_x", ncol = 2) + scale_fill_manual(labels = c ("Lytic", "Temperate"), values=pal2.flip) +theme(axis.text.x = element_text(angle = 25, hjust = 1)) + xlab("Enriched Gene") + ggtitle("INPHARED") + theme(legend.position = "bottom") #+ coord_flip()


rel
ggsave(here(figs_dir, "inph_lifestyle_AVG_enriched_relative.png"), height =6 ,width = 8)
 #ggsave(here("refseq/out-dir/rel_refseq_lifestyle_spor_enrich.png"), height =4 ,width = 4.5)

#geom_boxplot(binaxis = "y", stackdir = "center", position = "dodge") + geom_jitter(width = 0.2) + coord_flip()

```

```{r}





                                                
```

```{r}
 # reverse so top item plotted at top
```

```{r}
d.amg.sig.bubble <- d.amg.sig
d.amg.sig.bubble$life_bool <- ifelse(d.amg.sig.bubble$life_bool==TRUE, "Temperate", "Virulent")
d.amg.sig.bubble$enriched_facet <- ifelse(d.amg.sig.bubble$enriched=="temperate", "Temperate-Enriched Genes", "Virulent-Enriched Genes")
d.amg.sig.bubble$enriched_facet <- ifelse(d.amg.sig.bubble$enriched=="Not Enriched", "Not Lifestyle-Enriched Genes", d.amg.sig.bubble$enriched_facet)
#d.amg.sig.bubble <- subset(d.amg.sig, d.amg.sig$enriched_facet=="temperate")

pathway_levels <- d.amg.sig.bubble %>%
  distinct(COG.broad, comp3) %>%
  arrange(COG.broad, comp3) %>%
  pull(comp3)

d.amg.sig.bubble <- d.amg.sig.bubble %>%
  mutate(comp3 = factor(comp3, levels = pathway_levels))

p <- ggplot(d.amg.sig.bubble, aes(x = life_bool, y = comp3)) +
  geom_point(aes(size = rel), shape = 21, stroke = 0.6, fill="black") +
 scale_size_area(limits = c(0, 55), max_size = 8) +
  # control max bubble diameter
  theme_minimal(base_size = 12) +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(size = 11, face = "bold"),
    axis.text.y = element_text(size = 10),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank()
  ) +facet_wrap(~ enriched_facet, scales = "free_y", ncol = 2)  

p

# Add a colored strip at the LEFT that corresponds to pathway categories
strip_df <- unique(select(d.amg.sig.bubble, enriched_facet, COG.broad, comp3))
strip_df$COG.broad <- as.factor(strip_df$COG.broad)
strip_df <- strip_df %>% mutate(xpos = as.numeric(COG.broad))

strip_x <- min(strip_df$xpos) - 0.8   # ← ONLY CHANGE (was max + offset)

strip_df <- strip_df %>%
  select(COG.broad, comp3, enriched_facet) %>%
  distinct() %>%
  mutate(x = strip_x, xend = strip_x + 0.4)

p <- p +
  geom_tile(
    data = strip_df,
    aes(x = x, y = comp3, fill = COG.broad),
    width = 0.4,
    height = 0.9,
    inherit.aes = FALSE
  ) +
  coord_cartesian(clip = "off")

# Add legend and show
temp.gg <- p + guides(size = guide_legend(title = "Gene Category Proportion (%) "), fill=guide_legend(""))
temp.gg
ggsave(here(figs_dir, "inph_AVG_bubbleplot_Enrich.png"), height =5 ,width = 12)
```
```{r}
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(cowplot)
# -------------------------
# Create a dedicated legend plot (uniform keys for all levels)
# -------------------------
legend_df <- data.frame(COG = all_cogs, x = seq_along(all_cogs), y = 1)

legend_plot <- ggplot(legend_df, aes(x = x, y = y, fill = COG)) +
  geom_point(shape = 21, size = 5, stroke = 0.6) +
  scale_fill_manual(values = cog_colors, drop = FALSE) +
  guides(fill = guide_legend(title = "COG broad category", ncol = 1),
         size = "none") +
  theme_void() +
  theme(legend.position = "right",
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 11))

legend_grob <- cowplot::get_legend(legend_plot)

# -------------------------
# Assemble with cowplot using the dedicated legend_grob
# -------------------------
left_col <- plot_grid(p_top, p_bottom, ncol = 1, align = "v", rel_heights = c(2, 1))
main_grid <- plot_grid(left_col, p_long, ncol = 2, rel_widths = c(1, 1))

final_plot <- plot_grid(main_grid, legend_grob, ncol = 2, rel_widths = c(1, 0.28))

print(final_plot)


```



```{r}
# Accurate size legend + dedicated fill legend + cowplot layout
# Assumes d.amg.sig exists with columns:
#   life_bool (logical), enriched (character), COG.broad (factor/char), comp3 (pathway), rel (numeric)

library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(cowplot)
library(here)   # optional if saving

# -------------------------
# Shared size-scale definition (single source of truth)
# -------------------------
size_min_observed <- min(d.amg.sig.bubble$rel[d.amg.sig.bubble$rel > 0], na.rm = TRUE) # e.g. 0.1
size_limits <- c(0.05, 55)
size_max    <- 8
size_breaks <- c(0.05, 1, 10, 20, 30, 40, 50)
size_labels <- as.character(size_breaks)

# -------------------------
# Data prep
# -------------------------
d.amg.sig.bubble <- d.amg.sig %>%
  mutate(
    life_bool = ifelse(life_bool == TRUE, "Temperate", "Virulent"),
    enriched_facet = dplyr::case_when(
      enriched == "temperate"    ~ "Temperate-Enriched Genes",
      enriched == "Not Enriched" ~ "Not Lifestyle-Enriched Genes",
      TRUE                       ~ "Virulent-Enriched Genes"
    )
  )

enriched_order <- c(
  "Temperate-Enriched Genes",
  "Virulent-Enriched Genes",
  "Not Lifestyle-Enriched Genes"
)
d.amg.sig.bubble$enriched_facet <- factor(d.amg.sig.bubble$enriched_facet, levels = enriched_order)

# keep comp3 ordering consistent across panels
pathway_levels <- d.amg.sig.bubble %>%
  distinct(COG.broad, comp3) %>%
  arrange(COG.broad, comp3) %>%
  pull(comp3)
d.amg.sig.bubble$comp3 <- factor(d.amg.sig.bubble$comp3, levels = pathway_levels)

# -------------------------
# Tiles (left colored strip) helper
# -------------------------
strip_df_global <- d.amg.sig.bubble %>%
  select(enriched_facet, COG.broad, comp3) %>%
  distinct() %>%
  mutate(COG.broad = as.factor(COG.broad), xpos = as.numeric(COG.broad))

strip_x <- min(strip_df_global$xpos) - 0.8
strip_df_global <- strip_df_global %>% mutate(x = strip_x, xend = strip_x + 0.4)

# -------------------------
# Full set of COG levels and named colors
# -------------------------
all_cogs <- sort(unique(as.character(d.amg.sig.bubble$COG.broad)))
d.amg.sig.bubble$COG.broad <- factor(as.character(d.amg.sig.bubble$COG.broad), levels = all_cogs)

base_colors <- brewer.pal(min(8, max(3, length(all_cogs))), "Set2")
cog_colors <- setNames(colorRampPalette(base_colors)(length(all_cogs)), all_cogs)

# -------------------------
# Plot builder: uses the shared size scale (size_limits, size_max)
# -------------------------
build_plot <- function(df, facet_level) {
  ggplot(df, aes(x = life_bool, y = comp3)) +
    geom_point(aes(size = rel), shape = 21, stroke = 0.6, fill = "black") +
    scale_size_area(limits = size_limits, max_size = size_max) +
    scale_fill_manual(values = cog_colors, drop = FALSE) +
    theme_minimal(base_size = 12) +
    theme(
      axis.title = element_blank(),
      axis.text.x = element_text(size = 11, face = "bold"),
      axis.text.y = element_text(size = 10),
      panel.grid.major.y = element_blank(),
      panel.grid.minor = element_blank()
    ) +
    coord_cartesian(clip = "off") -> p

  # add colored tiles for pathways present in this panel
  strip_df_sub <- strip_df_global %>% filter(enriched_facet == facet_level & comp3 %in% unique(df$comp3))
  p <- p + geom_tile(
    data = strip_df_sub,
    aes(x = x, y = comp3, fill = COG.broad),
    width = 0.4, height = 0.9, inherit.aes = FALSE
  )

  # hide guides on panel plots (legend will come from dedicated legend plot)
  p <- p + guides(fill = "none", size = "none")

  p
}

# -------------------------
# Build main panels
# -------------------------
p_top <- build_plot(d.amg.sig.bubble %>% filter(enriched_facet == "Temperate-Enriched Genes"),
                    "Temperate-Enriched Genes") + ggtitle("A) Temperate-Enriched Genes")

p_bottom <- build_plot(d.amg.sig.bubble %>% filter(enriched_facet == "Virulent-Enriched Genes"),
                       "Virulent-Enriched Genes") + ggtitle("B) Virulent-Enriched Genes")

p_long <- build_plot(d.amg.sig.bubble %>% filter(enriched_facet == "Not Lifestyle-Enriched Genes"),
                     "Not Lifestyle-Enriched Genes") + ggtitle("C) Genes Not Enriched By Lifestyle")

# -------------------------
# Dedicated legend plot (uses same size scale: size_limits, size_max, size_breaks)
# - fill legend: one row per COG -> uniform filled-circle keys via override.aes
# - size legend: rows for each size_break so legend bubbles match mapping exactly
# -------------------------
# data for fill legend (one row per COG)
fill_legend_df <- data.frame(
  COG = all_cogs,
  x = seq_along(all_cogs),
  y = rep(2, length(all_cogs)),
  size_val = rep(mean(size_breaks), length(all_cogs))
)

# data for size legend (one row per break value)
size_legend_df <- data.frame(
  COG = rep(all_cogs[1], length(size_breaks)),        # arbitrary COG used for fill (single fill is OK)
  x = seq_along(size_breaks) + length(all_cogs) + 1,
  y = rep(1, length(size_breaks)),
  size_val = size_breaks
)

legend_df <- bind_rows(fill_legend_df, size_legend_df)

legend_plot <- ggplot(legend_df, aes(x = x, y = y, fill = COG, size = size_val)) +
  geom_point(shape = 21, stroke = 0.6)  +
  scale_fill_manual(values = cog_colors, drop = FALSE) +
  scale_size_area(limits = size_limits, breaks = size_breaks, labels = size_labels, max_size = size_max) +
  guides(
    fill = guide_legend(title = "COG broad category", ncol = 1,
                        override.aes = list(shape = 22, size = 5, alpha = 1)),
    size = guide_legend(
    title = "Gene Category Proportion (%)",
    override.aes = list(
      shape = 21,
      fill  = "black",
      colour = "black",
      alpha = 1
    )
  )) +
  theme_void() +
  theme(
    legend.position = "right",
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 11)
  )

legend_grob <- cowplot::get_legend(legend_plot)

# -------------------------
# Assemble final figure with cowplot
# -------------------------
left_col <- plot_grid(p_top, p_bottom, ncol = 1, align = "v", rel_heights = c(2, 1))
main_grid <- plot_grid(left_col, p_long, ncol = 2, rel_widths = c(1, 1))
final_plot <- plot_grid(main_grid, legend_grob, ncol = 2, rel_widths = c(1, 0.28))

# display
print(final_plot)

ggsave(here(figs_dir, "inph_AVG_bubbleplot_Enrich.png"), height =6 ,width = 14)
# optional: save (create dir if needed)
# out_dir <- here::here("figs")
# if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
# ggsave(file.path(out_dir, "inph_AVG_bubbleplot_size_accurate.png"),
#        plot = final_plot, width = 12, height = 6, dpi = 300)

```




