---
title: "R Notebook"
output: html_notebook
---

```{r}
library(here)
library(tidyverse)
library(PNWColors)
library(knitr)
library(cowplot)
library(ggrepel)
library(dplyr)


here::here()
data_dir <- here("03_func", "inphared")
meta_dir <- here("03_func", "03_metadata")
raw_dir <- here("03_func", "inphared", "03_inph_raw")
figs_dir <- here("03_func", "inphared", "figs")

pal2 <- c("#015b58", "#5962b5")
pal2.flip <- c("#5962b5", "#015b58")
hmm <- read.csv(here(data_dir, "inphared_hmm_comp2.csv"), row.names=1 ) ##d_amg

hmm$indiv_cat <- hmm$Nog.abbrev
hmm$indiv_cat <- ifelse(hmm$COGlet=="Ph" | hmm$COGlet=="Aux", hmm$detailed, hmm$indiv_cat)
hmm$indiv_cat <- ifelse(hmm$COG.broad=="SPORULATION", "Sporulation", hmm$indiv_cat)
hmm$indiv_cat <- ifelse(hmm$indiv_cat=="Unknown Phage-Associated" | hmm$indiv_cat=="No hits (0)" | hmm$indiv_cat=="Unknown function (S)" , "Unknown (S)", hmm$indiv_cat)
hmm$COG.broad <- ifelse(hmm$indiv_cat=="Unknown (S)", "POORLY CHARACTERIZED", hmm$COG.broad)
```

###Calculate functional distribution for INDIVIDUAL phages
```{r}
hmm.indiv <- hmm
hmm.indiv$tally <- 1



###count number of ORFS per phage
prot.phage <- hmm.indiv %>%
  group_by(Host, predicted_label) %>%
  summarise(TotalORF.perPhage = sum(tally))

prot.phage <- unite(prot.phage, iso_phage, Host, predicted_label, sep = "_", remove=TRUE)


### count number of ORFs per phage by functional category (+ keep track of genus, intact estimates)
indiv.phage <- hmm.indiv %>%
     group_by(Host, sporulation_hit, COGlet, COG.broad, detailed, comp, comp2, comp3, indiv_cat, spor, predicted_label) %>%
  # group_by(Host, sporulation_hit, COG.broad, Cog.cat, COGlet, detailed, comp, comp2, predicted_label) %>%
  summarise(new.freq = sum(tally))

indiv.phage<- unite(indiv.phage, iso_phage, Host, predicted_label, sep = "_", remove=FALSE)



##combine count data from above
indiv.phage.freq <- merge(prot.phage, indiv.phage, by="iso_phage", all=TRUE)

### calc the percentage a category takes up that portin of the phage genome (e.g. total genome is 20 genomes, 2 of which are carbon metabolism (2/20 = 10% of genome))
indiv.phage.freq$perc.fq <- indiv.phage.freq$new.freq/indiv.phage.freq$TotalORF.perPhage*100


phage.func.indiv <- indiv.phage.freq

###Calculate functional distribution for all phages of a Bacterial host

### count number of ORFS per bacterial host
prot.iso <- hmm.indiv %>%
  group_by(predicted_label) %>%
  summarise(TotalORF.perIso = sum(tally))


### count number of hits to a Category per bacterial host
indiv.iso <- hmm.indiv %>%
    group_by(sporulation_hit, COGlet, COG.broad, detailed, comp, comp2, comp3, indiv_cat, spor, predicted_label) %>%
  # group_by(sporulation_hit, COG.broad, Cog.cat, COGlet, detailed, comp, comp2, predicted_label) %>%
  summarise(new.freq = sum(tally))


### merge count data
indiv.iso.freq <- merge(prot.iso, indiv.iso, by="predicted_label", all=TRUE)

### find percentage of ORF Category that contributes to a bacterial host's "phage pangenome"
indiv.iso.freq$perc.fq <- indiv.iso.freq$new.freq/indiv.iso.freq$TotalORF.perIso*100

phage.func.iso <- indiv.iso.freq
```


```{r}


phage.func.iso$facet1 <- "All Genes"

phage.func.iso <- unite(phage.func.iso, facet2, spor, predicted_label, sep = "_", remove=FALSE)

### for isos with no phage, set the "intact" status to degraded so they are not lost when graphing


aux.iso.meta <- subset(phage.func.iso, phage.func.iso$comp!="Unknown (S, No Hits)" & phage.func.iso$comp!="Phage-associated")
aux.iso.meta$facet1 <- "Auxillary Genes"

test_phage.func.iso_facet <- rbind(phage.func.iso, aux.iso.meta)


# Ensure comp has the right order
#test_phage.func.iso_facet$comp3 <- factor(test_phage.func.iso_facet$comp3, 
#                                         levels = desired_order2)
```



```{r}
test_phage.func.iso_facet <- subset(test_phage.func.iso_facet, test_phage.func.iso_facet$facet1=="All Genes")
```

```{r}
test_phage.func.iso_facet <- subset(test_phage.func.iso_facet, test_phage.func.iso_facet$facet1=="All Genes")
d.amg.sig.bubble <- test_phage.func.iso_facet

d.amg.sig.bubble$facet2 <- ifelse(d.amg.sig.bubble$facet2=="Spor_temperate", "Temperate", "Virulent")
#d.amg.sig.bubble$enriched_facet <- ifelse(d.amg.sig.bubble$enriched_facet=="temperate", "Temperate-Enriched Genes", "Virulent-Enriched Genes")

#d.amg.sig.bubble$comp3 <- ifelse(d.amg.sig.bubble$detailed=="Unknown Phage-Associated", "Unknown Phage-Associated", d.amg.sig.bubble$comp3)
#d.amg.sig.bubble <- subset(d.amg.sig, d.amg.sig$enriched_facet=="temperate")

pathway_levels <- d.amg.sig.bubble %>%
  distinct(COG.broad, indiv_cat) %>%
  arrange(COG.broad, indiv_cat) %>%
  pull(indiv_cat)

d.amg.sig.bubble <- d.amg.sig.bubble %>%
  mutate(indiv_cat = factor(indiv_cat, levels = pathway_levels))

p <- ggplot(d.amg.sig.bubble, aes(x = facet2, y = indiv_cat)) +
  geom_point(aes(size = perc.fq), shape = 21, stroke = 0.6, fill="black") +
 scale_size_area( max_size = 8) +
  # control max bubble diameter
  theme_minimal(base_size = 12) +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(size = 11, face = "bold"),
    axis.text.y = element_text(size = 10),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank()
  )  

p

# Add a colored strip at the LEFT that corresponds to pathway categories
strip_df <- unique(select(d.amg.sig.bubble, COG.broad, indiv_cat))
strip_df$COG.broad <- as.factor(strip_df$COG.broad)
strip_df <- strip_df %>% mutate(xpos = as.numeric(COG.broad))

strip_x <- min(strip_df$xpos) - 0.8   # ← ONLY CHANGE (was max + offset)

strip_df <- strip_df %>%
  select(COG.broad, indiv_cat) %>%
  distinct() %>%
  mutate(x = strip_x, xend = strip_x + 0.4)

p <- p +
  geom_tile(
    data = strip_df,
    aes(x = x, y = indiv_cat, fill = COG.broad),
    width = 0.4,
    height = 0.9,
    inherit.aes = FALSE
  ) +
  coord_cartesian(clip = "off")

# Add legend and show
all.gg <- p + guides(size = guide_legend(title = "Gene Category Proportion (%) "), fill=guide_legend("Broad Gene Category"))
all.gg



```

```{r}
d.amg.sig.bubble2 <- subset(d.amg.sig.bubble, d.amg.sig.bubble$COG.broad!="PHAGE" & d.amg.sig.bubble$COG.broad!="POORLY CHARACTERIZED")

#d.amg.sig.bubble2$perc.fq <- d.amg.sig.bubble2$perc.fq 
#d.amg.sig.bubble$comp3 <- ifelse(d.amg.sig.bubble$detailed=="Unknown Phage-Associated", "Unknown Phage-Associated", d.amg.sig.bubble$comp3)
#d.amg.sig.bubble <- subset(d.amg.sig, d.amg.sig$enriched_facet=="temperate")

pathway_levels <- d.amg.sig.bubble2 %>%
  distinct(COG.broad, indiv_cat) %>%
  arrange(COG.broad, indiv_cat) %>%
  pull(indiv_cat)

d.amg.sig.bubble <- d.amg.sig.bubble2 %>%
  mutate(indiv_cat = factor(indiv_cat, levels = pathway_levels))

p <- ggplot(d.amg.sig.bubble2, aes(x = facet2, y = indiv_cat)) +
  geom_point(aes(size = perc.fq), shape = 21, stroke = 0.6, fill="black") +
 scale_size_area( max_size = 8) +
  # control max bubble diameter
  theme_minimal(base_size = 12) +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(size = 11, face = "bold"),
    axis.text.y = element_text(size = 10),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank()
  )  

#p

# Add a colored strip at the LEFT that corresponds to pathway categories
strip_df <- unique(select(d.amg.sig.bubble2, COG.broad, indiv_cat))
strip_df$COG.broad <- as.factor(strip_df$COG.broad)
strip_df <- strip_df %>% mutate(xpos = as.numeric(COG.broad))

strip_x <- min(strip_df$xpos) - 0.8   # ← ONLY CHANGE (was max + offset)

strip_df <- strip_df %>%
  select(COG.broad, indiv_cat) %>%
  distinct() %>%
  mutate(x = strip_x, xend = strip_x + 0.4)

p <- p +
  geom_tile(
    data = strip_df,
    aes(x = x, y = indiv_cat, fill = COG.broad),
    width = 0.4,
    height = 0.9,
    inherit.aes = FALSE
  ) +
  coord_cartesian(clip = "off")

# Add legend and show
temp.gg <- p + guides(size = guide_legend(title = "Value"))
temp.gg
ggsave(here(figs_dir, "inph_AVG_bubbleplot_COGall.png"), height =8 ,width = 12)
```