---
title: "R Notebook"
output: html_notebook
---


```{r}
library(here)
library(dplyr)
library(tidyr)
library(purrr)

# Labels (adjust if needed)
temp_label <- "Temperate"
lytic_label <- "Lytic"


inph <- read.csv(here("00_data", "03_func_data", "output", "inph_functional_data.csv"),row.names=1) 
inph<- subset(inph, inph$newgtdb_Phylum=="Bacillota" &  inph$f_spor==TRUE & inph$SporHitRelax==TRUE)
inph <- subset(inph, inph$completeness>90 & inph$contamination<0.5) 



gsv <- read.csv(here("00_data", "03_func_data", "output", "GSV_functional_data.csv"),row.names=1)
gsv<- subset(gsv, gsv$newgtdb_Phylum=="Bacillota" &  gsv$f_spor==TRUE & gsv$SporHitRelax==TRUE)
gsv <- subset(gsv, gsv$completeness>90 & gsv$contamination<0.5) 




uhgv  <- read.csv(here("00_data", "03_func_data", "output", "UHGV_functional_data.csv"),row.names=1) 
uhgv<- subset(uhgv, uhgv$newgtdb_Phylum=="Bacillota" &  uhgv$f_spor==TRUE & uhgv$SporHitRelax==TRUE)
uhgv <- subset(uhgv, uhgv$completeness>90 & uhgv$contamination<0.5) 

source(here("utility-scripts", "03_func_fishertest_genecounts.R"),)
#hmm<- subset(hmm, hmm$completeness >=
```

```{r}

inph.list <- prepare_gene_counts(inph, phage_col = "Accession", gene_col  = "spor_gene_name", lifestyle_col = "lifestyle", cog_col = "COGlet", temp_label = "Temperate", lytic_label = "Lytic")

gsv.list <- prepare_gene_counts(gsv, phage_col = "Accession", gene_col  = "spor_gene_name", lifestyle_col = "lifestyle", cog_col = "COGlet", temp_label = "Temperate", lytic_label = "Lytic")

uhgv.list <- prepare_gene_counts(uhgv, phage_col = "Accession", gene_col  = "spor_gene_name", lifestyle_col = "lifestyle", cog_col = "COGlet", temp_label = "Temperate", lytic_label = "Lytic")


inph.gene_counts    <- inph.list$gene_counts
inph.total_temp     <- inph.list$total_temp
inph.total_lytic    <- inph.list$total_lytic

gsv.gene_counts    <- gsv.list$gene_counts
gsv.total_temp     <- gsv.list$total_temp
gsv.total_lytic    <- gsv.list$total_lytic

uhgv.gene_counts    <- uhgv.list$gene_counts
uhgv.total_temp     <- uhgv.list$total_temp
uhgv.total_lytic    <- uhgv.list$total_lytic

```

```{r}


inph.fisher <- compute_fisher_minimal(
  inph.gene_counts,
  inph.total_temp,
  inph.total_lytic
)

inph.fisher$dataset <- "INPHARED"

gsv.fisher <- compute_fisher_minimal(
  gsv.gene_counts,
  gsv.total_temp,
  gsv.total_lytic
)

gsv.fisher$dataset <- "GSV"

uhgv.fisher <- compute_fisher_minimal(
  uhgv.gene_counts,
  uhgv.total_temp,
  uhgv.total_lytic
)

uhgv.fisher$dataset <- "UHGV"
```


```{r}

#all.fisher <- bind_rows(inph.fisher, gsv.fisher, uhgv.fisher)


all.fisher <- bind_rows(inph.fisher, uhgv.fisher) 
p.signif <- 1e-3

k_threshold <- 5

all.fisher <- subset(all.fisher, all.fisher$gene_name!="lytD" & all.fisher$gene_name!="nlpD")


all.fisher <-  all.fisher %>%  mutate(p.adj = signif (p.adjust(p_two_sided, method = "BH"),5), neg_log10_p = -log10(p.adj),) %>% 
  # mark significantly enriched genes
   mutate(significant = (p.adj < p.signif) & (prevalence > k_threshold)) 

```
### plot
```{r}
library(ggplot2)
library(ggrepel)

list <- read.csv(here("03_func", "inphared","figs", "inph_spor_enrich_sig_v2_eb.csv"))
list <- select(list, gene_name, type, function., sporulation_impact, localization, stage )
list <- subset(list, list$sporulation_impact!="remove")


sig.fisher <- subset(all.fisher, all.fisher$significant==TRUE)

sig.fisher <- merge(sig.fisher, list, by="gene_name", all.x=TRUE, all.y=FALSE)
sig.fisher[is.na(sig.fisher)] <- "Unknown"



ggplot(sig.fisher, aes(x =plot_OR, y = neg_log10_p)) +
  geom_point(aes(size = plot_OR,
                 color = direction),
             alpha = 0.7) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  scale_size_continuous(name = "|log2(OR)|") +
  scale_color_manual(values = c(
    "Temperate" = "#1f78b4",
    "Lytic" = "#e31a1c",
    "Equal" = "grey70"
  )) +
  labs(
    x = "log2(Odds Ratio)",
    y = "-log10(BH-adjusted p-value)",
    color = "Enriched in"
  ) +
  theme_minimal() +  # Add gene labels
  geom_text_repel(aes(label = gene_name),
                  size = 3,
                  max.overlaps = Inf)  + facet_grid(dataset~direction) 



ggplot(sig.fisher, aes(x =plot_OR, y = neg_log10_p)) +
  geom_point(aes(size = plot_OR,
                 color = sporulation_impact),
             alpha = 0.7) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  scale_size_continuous(name = "|log2(OR)|") +
  labs(
    x = "log2(Odds Ratio)",
    y = "-log10(BH-adjusted p-value)",
    color = "Category"
  ) +
  theme_minimal() +  # Add gene labels
  geom_text_repel(aes(label = gene_name),
                  size = 3,
                  max.overlaps = Inf)  + facet_grid(dataset~direction) 


ggplot(sig.fisher, aes(x =plot_OR, y = neg_log10_p)) +
  geom_point(aes(size = plot_OR,
                 color = function.),
             alpha = 0.7) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  scale_size_continuous(name = "|log2(OR)|") +
  labs(
    x = "log2(Odds Ratio)",
    y = "-log10(BH-adjusted p-value)",
    color = "Category"
  ) +
  theme_minimal() +  # Add gene labels
  geom_text_repel(aes(label = gene_name),
                  size = 3,
                  max.overlaps = Inf)  + facet_grid(dataset~direction) 

```


```{r}


pathway_levels <- sig.fisher %>%
  distinct(sporulation_impact, stage, localization, gene_name) %>%
  arrange(sporulation_impact, stage, localization, gene_name) %>%
  pull(gene_name)


sig.fisher.bubble <- sig.fisher %>%
  mutate(gene_name = factor(gene_name, levels = pathway_levels))

sig.fisher.bubble <- subset(sig.fisher.bubble, sig.fisher.bubble$sporulation_impact!="Unknown")

p <- ggplot(sig.fisher.bubble, aes(x = dataset, y = gene_name)) +
  geom_point(aes(size = plot_OR,
                 color = direction),
             alpha = 0.7) +

  scale_color_manual(values = c(
    "Temperate" = "#1f78b4",
    "Lytic" = "#e31a1c",
    "Equal" = "grey70"
  )) +
  
  labs(
    x = "Dataset",
    y = "Gene",
    color = "Enriched in",
    size = "|log2(OR)|"
  ) +
  
  theme_minimal() 

strip_df <- unique(select(sig.fisher.bubble, sporulation_impact, stage, localization, gene_name))
strip_df$sporulation_impact <- as.factor(strip_df$sporulation_impact)
strip_df$stage <- as.factor(strip_df$stage)
strip_df$localization <- as.factor(strip_df$localization)
strip_df <- strip_df %>% mutate(xpos = as.numeric(sporulation_impact))

strip_x <- min(strip_df$xpos) - 0.8   # ← ONLY CHANGE (was max + offset)

strip_df <- strip_df %>%
  select(sporulation_impact, stage, localization, gene_name) %>%
  distinct() %>%
  mutate(x = strip_x, xend = strip_x + 0.4)

p <- p +
  geom_tile(
    data = strip_df,
    aes(x = x, y = gene_name, fill = sporulation_impact),
    width = 0.4,
    height = 0.9,
    inherit.aes = FALSE
  ) +
  coord_cartesian(clip = "off")



# Add legend and show
all.gg <- p + guides(size = guide_legend(title = "Gene Category Proportion (%) "), fill=guide_legend("Broad Gene Category"))

all.gg #+ facet_wrap

```


```{r}
ggplot(sig.fisher, aes(x = dataset, y = reorder(gene_name, plot_OR))) +
  geom_point(aes(size = plot_OR,
                 color = direction),
             alpha = 0.7) +

  scale_color_manual(values = c(
    "Temperate" = "#1f78b4",
    "Lytic" = "#e31a1c",
    "Equal" = "grey70"
  )) +
  
  labs(
    y = "Gene",
    color = "Enriched in",
    size = "|log2(OR)|"
  ) +
  
  theme_minimal() +
  theme(
    axis.title.x = element_blank(),
    axis.text.x  = element_blank(),
    axis.ticks.x = element_blank()
  ) #+ facet_wrap(~stage, scales = "free_y")

```



