---
title: "R Notebook"
output: html_notebook
---
```{r}
library(here)
library(tidyverse)

here::here()

data_dir <- here("isolate_dbs/inphared/")

raw_dir <- here("isolate_dbs/inphared/")
gtdb_dir <- here("isolate_dbs/gtdb/")

inph_dir <- here("refseq/raw_data/")

inph <- read.delim2(here(raw_dir, "1Jan2025_data.tsv"))

phatyp <- read.delim2(here(inph_dir, "32125_resfseq_phatyp_prediction.tsv"))

style <- read.delim2(here(raw_dir, "inphared_phastyle_predictions.tsv"))


## dan sporulation classifying groups
dan.tax <- read.csv(here(gtdb_dir, "gtdb_families_sporulation.csv" ))
dan.tax$gtdb_f<- gsub('f__', '', dan.tax$gtdb_f) 
gtdb.tax <- read.csv(here(gtdb_dir, "gtdb-taxonomy-table.csv" ))
gtdb.tax <- subset(gtdb.tax, gtdb.tax$Domain=="Bacteria")
colnames(gtdb.tax) <- paste0("newgtdb_", colnames(gtdb.tax))


##phage lifestyle information
### some inphared phages missing
phagescope <- read.delim2(here(inph_dir, "22825_refseq_phagescope.tsv" ))   # d_vir
#phagescope <- subset(phagescope, phagescope$Phage_source=="RefSeq" | phagescope$Phage_source=="GenBank")
phagescope$phage<- gsub('.[^.]*$', '', phagescope$Phage_ID) 


### phatyp vs. phagescope
all <- merge(inph, phatyp, by="Accession", all.x=TRUE, all.y=TRUE) #%>%

all <- merge(all, style, by.x="Accession", by.y="fasta_id", all.x=TRUE, all.y=TRUE)

all2 <- all[,c(1:3,5,15,27,34)]

```






### PhaTYP vs. PhageSCOPE

```{r}
test <- merge(inph, phatyp, by="Accession", all.x=TRUE, all.y=TRUE) #%>%
 # merge(phagescope, by.y="phage", all.x=TRUE, all.y=TRUE)

test <- merge(test, phagescope, by.x="Accession", by.y="phage", all.x=TRUE, all.y=FALSE)
  
test[is.na(test)] <- "NA"

test <- subset(test, test$TYPE!="NA")
test <- subset(test, test$Lifestyle!="NA")

test <- test[,c(1,2,34,47)]

test$match <- ifelse(test$Lifestyle==test$TYPE, TRUE, FALSE)

#1378  total
# 115 FALSE (8.3% disagrement) 
# 1263 (91.6% share)

## 392 bacillus phage
## 68 false (17.3%)
## 324 true (82.6%)

## 93 clostridia
# 6 false (6.45%)
# 87 true (93.5%)

## 66 listeria phage
# 3 false (4.5%)
## 63 true  ( 95.45%)

## 288 staphyloccus
# 279 TRUE (96.8%)

### leaning toward type being more accurate? except for wbeta lol 

## p larvae phage thought to be lytic but this paper says it is actually temperate: ## https://pmc.ncbi.nlm.nih.gov/articles/PMC4510184/ 
```

